### ISSUE TITLE
Update CTL with better information about conformance classes.

### ISSUE THREAD

**Issue by keshavnangare** [opengeospatial/ets-sps20#1]
The test needs to be updated to better provide information about the grouping of the conformance class and determination about which ones are the basic conformance classes needed for certification.

Changes that are required are described here:

https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes

**Comment by lgoltz** [comment]
In the [specification](http://portal.opengeospatial.org/files/?artifact_id=38478) are several conformance classes described. In the test suite the sps:Main test has three subtests:
 * sps:ows-main
 * sps:general-main
 * sps:core-main

I think all of them should be marked as conformance class and basic.

**Comment by lgoltz** [comment]
RI for testing: http://sensorweb.demo.52north.org/52n-sps-2.0/sps?request=GetCapabilities

**Comment by lgoltz** [comment]
Configured as proposed in https://github.com/opengeospatial/ets-sps20/issues/1#issuecomment-380374569: PR: #2
